version: 0.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macos
  - macos-mojave
matrix:
  allow_failures:
    - test_category: FailsOnWindows
    - image: Visual Studio 2019
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- dotnet restore src/Vlingo.Http.sln
build:
  project: src/Vlingo.Http.sln
  verbosity: minimal
  publish_nuget: true
for:
  - matrix:
      only:
        - image: Visual Studio 2019
    before_test:
      - ps: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
    after_test:
      - ps: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
test_script:
- dotnet test src/Vlingo.Http.Tests
deploy:
- provider: NuGet
  api_key:
    secure: S7SGXqFTXTOVbVLP45Ofyf/iTsIOr9o0F/QEeQkaUMqb/PkwWjXK6+CF4WAqbfWr
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
